#!/bin/sh

 if [ -z "${GITHUB_TOKEN}" ]; then
     echo "error: GITHUB_TOKEN is not defined"
     exit 1
 fi

curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/users/"$1"/gpg_keys
